INSERT INTO players (name) VALUES ('Alex');
INSERT INTO players (name) VALUES ('Igor');
INSERT INTO players (name) VALUES ('Sergei');
INSERT INTO players (name) VALUES ('Dmitry');
INSERT INTO players (name) VALUES ('Vlad');
INSERT INTO players (name) VALUES ('Tima');
INSERT INTO players (name) VALUES ('Mr tractor');
INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 3);
INSERT INTO matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO matches (player1, player2, winner) VALUES (2, 1, 1);
INSERT INTO matches (player1, player2, winner) VALUES (1, 4, 1);
INSERT INTO matches (player1, player2, winner) VALUES (4, 3, 4);
INSERT INTO matches (player1, player2, winner) VALUES (5, 7, 5);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 4);
